sudo: required
services:
  - docker

before_install:
  - docker build -t fabio90h/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run fabio90h/react-test npm test -- --coverage

after_success:
  - docker build -t fabio90h/sportlight-client ./frontend
  - docker build -t fabio90h/sportlight-server ./server
  - docker build -t fabio90h/sportlight-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push fabio90h/sportlight-client
  - docker push fabio90h/sportlight-server
  - docker push fabio90h/sportlight-nginx