sudo: required
services:
  - docker

before_install:
  - docker build -t "$DOCKER_ID"/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run "$DOCKER_ID"/react-test npm test -- --coverage

after_success:
  - docker build -t "$DOCKER_ID"/sportlight-client ./frontend
  - docker build -t "$DOCKER_ID"/sportlight-server ./server
  - docker build -t "$DOCKER_ID"/sportlight-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push "$DOCKER_ID"/sportlight-client
  - docker push "$DOCKER_ID"/sportlight-server
  - docker push "$DOCKER_ID"/sportlight-nginx